import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ShowSideBar from "@/app/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex antialiased`}
      >
        <aside id="sidebar" className="w-52 bg-blue-50 h-screen flex flex-col"><div>
            <div className="text-green-500 font-bold text-2xl border-4"><p className="text-center">Main</p> </div>
          </div>
          </aside>
          <ShowSideBar />
        {children}
      </body>
    </html>
  );
}
